# Generated by Django 3.1.4 on 2021-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgrimetricsAssignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsandwichorder',
            name='base',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='createsandwichorder',
            name='cheese',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='createsandwichorder',
            name='extra',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='createsandwichorder',
            name='meat_one',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='createsandwichorder',
            name='meat_two',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='createsandwichorder',
            name='sauce',
            field=models.CharField(default='', max_length=50),
        ),
    ]
