# Generated by Django 3.1.4 on 2021-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgrimetricsAssignment', '0002_auto_20211202_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsandwichorder',
            name='table_number',
            field=models.IntegerField(default=0),
        ),
    ]
