# Generated by Django 3.1.4 on 2021-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgrimetricsAssignment', '0004_auto_20211202_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsandwichorder',
            name='time',
            field=models.DateField(default=''),
        ),
    ]
